name: New release action
run-name: ${{ github.repository }} release ${{ github.ref_name }}

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  CreateEasyConfigForRelease:
    name: Create EasyConfig in take-it-easyconfig repo for new release.
    runs-on: ubuntu-slim
    environment: releases
    steps:
      - name: Send pull-request
        run: |
              set -e
              set -u
              set -o pipefail
              #
              # In order for this code to work we need:
              #  * The team invited to review the PR must be public.
              #  * The bot account used to create the PR:
              #     * Must NOT be a member of the team invited to review the PR.
              #     * Must have a Personal Access Token (PAT)
              #        * Resource owner: ORGANISTION
              #        * with permissions/scope on REPOSITORY where the PR will be created - Contents: read & write
              #        * with permissions/scope on REPOSITORY where the PR will be created - Pull requests: read only
              #          This will automagically also assign:
              #        * with permissions/scope on REPOSITORY where the PR will be created - Metadata: read only
              #        * with permissions/scope on the ORGANISATION - Members: read only
              #        * with permissions/scope on the ORGANISATION - Projects: read only
              #  * The PAT created for the bot account with "resource owner" ORGANISATION
              #    will create a request for approval of that PAT in the ORGANISATION;
              #    An ORGANISATION admin needs to approve the PAT before it can be used.
              #  * The value of the PAT must be added as secret for the REPOSITORY repo
              #    and in the scope of an environment named "releases".
              #
              export GH_TELEMETRY=false
              ORGANISATION='molgenis'
              REPOSITORY='take-it-easyconfigs'
              MODULE_NAME="${{ github.event.repository.name }}"
              MODULE_NAME_LOWERCASE="${MODULE_NAME,,}"
              MODULE_VERSION="${{ github.ref_name }}"
              TOOLCHAIN_NAME='GCCcore'
              TOOLCHAIN_VERSION='11.3.0'
              MODULE_SPEC="${MODULE_NAME}/${MODULE_VERSION}-${TOOLCHAIN_NAME}-${TOOLCHAIN_VERSION}"
              EASYCONFIG_PATH="${MODULE_NAME_LOWERCASE:0:1}/${MODULE_NAME}/${MODULE_NAME}-${MODULE_VERSION}-${TOOLCHAIN_NAME}-${TOOLCHAIN_VERSION}.eb"
              #
              # Download release
              #
              curl -L \
                  --output "${MODULE_NAME}-${MODULE_VERSION}.tar.gz" \
                  "${{ github.server_url }}/${ORGANISATION}/${MODULE_NAME}/archive/refs/tags/${MODULE_VERSION}.tar.gz"
              CHECKSUM="$(shasum -a 256 "${MODULE_NAME}-${MODULE_VERSION}.tar.gz" | cut -d " " -f 1)"
              tar -xvzf "${MODULE_NAME}-${MODULE_VERSION}.tar.gz"
              #
              # Get modules and their versions from *.nf files.
              #
              readarray -t modules< <(find "./${MODULE_NAME}-${MODULE_VERSION}/" -name '*.nf' -print0 \
                  | xargs -0 awk '/module = \[/,/\]/' \
                  | sed 's/module = //' \
                  | tr -d '[' \
                  | tr -d ']' \
                  | tr -d "'" \
                  | tr ',' '\n' \
                  | tr -d '[:blank:]' \
                  | sort -u)
              declare -A module_versions
              for module in "${modules[@]}"; do
                  echo "Found module ${module%%/*} version ${module##*/}"
                  module_versions["${module%%/*}"]="${module##*/}"
              done
              #
              # Clone the remote repository.
              #
              git clone \
                  --depth=1 \
                  --branch=main \
                  "https://github.com/${ORGANISATION}/${REPOSITORY}.git"
              cd "${REPOSITORY}"
              #
              # Configure committer identity.
              #
              git config user.email 'analysis-jenkins[bot]@users.noreply.github.com'
              git config user.name 'analysis-jenkins[bot]'
              git config 'url.https://${{ secrets.TAKE_IT_EASYCONFIGS_PAT }}@github.com/.insteadOf' 'https://github.com/'
              #
              # Create a new feature branch for the changes.
              #
              git checkout -b "${MODULE_SPEC}"
              #
              # Create/update the EasyConfig.
              #
              cat << ENDOFEASYCONFIG > "${EASYCONFIG_PATH}"
              name = '${MODULE_NAME}'
              version = '${MODULE_VERSION}'

              homepage = 'https://github.com/${ORGANISATION}/${MODULE_NAME}/'
              description = """Nexflow ngs_dna pipeline used in the UMCG."""

              toolchain = {'name': '${TOOLCHAIN_NAME}', 'version': '${TOOLCHAIN_VERSION}'}
              easyblock = 'CmdCp'

              source_urls = [('https://github.com/${ORGANISATION}/%s/archive/' % (name))]
              sources = [('%s.tar.gz' % (version))]
              checksums = [('sha256', '${CHECKSUM}')]

              dependencies = [
                  ('BCFtools', '${module_versions['BCFtools']%-${TOOLCHAIN_NAME}-${TOOLCHAIN_VERSION}}'),
                  ('BEDTools', '${module_versions['BEDTools']%-${TOOLCHAIN_NAME}-${TOOLCHAIN_VERSION}}'),
                  ('gVCF2BED', '${module_versions['gVCF2BED']%-${TOOLCHAIN_NAME}-${TOOLCHAIN_VERSION}}'),
                  ('HTSlib', '${module_versions['HTSlib']%-${TOOLCHAIN_NAME}-${TOOLCHAIN_VERSION}}'),
              ]

              #
              # Sanity checking.
              #
              sanity_check_paths = {
                  'files': ['README.md', 'workflow_dragen.nf'],
                  'dirs': ['modules', 'scripts', 'tests']
              }

              moduleclass = 'bio'

              ENDOFEASYCONFIG
              echo '=============================================='
              #
              # Commit changes and push feature branch to origin.
              #
              git status
              echo '=============================================='
              git add "${EASYCONFIG_PATH}"
              git commit -m "New/updated EasyConfig for ${MODULE_SPEC}."
              echo '=============================================='
              git status
              echo '=============================================='
              git pull origin
              git push --force --set-upstream origin "${MODULE_SPEC}"
              echo '=============================================='
              git status
              echo '=============================================='
              #
              # Authorize GitHub CLI and create PR.
              #
              gh config set telemetry disabled
              echo "${{ secrets.TAKE_IT_EASYCONFIGS_PAT }}" | gh auth login --with-token
              echo '=============================================='
              gh pr edit \
                  "${MODULE_SPEC}" \
                  --body '' \
                  --title "Auto PR: New/updated EasyConfig for ${MODULE_SPEC}." \
                  --add-reviewer 'molgenis/analysis-team' \
                && gh pr reopen "${MODULE_SPEC}" \
                || gh pr create \
                  --body '' \
                  --title "Auto PR: New/updated EasyConfig for ${MODULE_SPEC}." \
                  --head "${MODULE_SPEC}" \
                  --base 'main' \
                  --reviewer 'molgenis/analysis-team'